//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public partial class DepartmentCreate
    {
        [Required]
        [StringLength(20)]
        public string Name { get; set; }
        [Required]
        [Range(0, 9999, ErrorMessage = "超過部門預算({0})，請輸入介於 {1} 到 {2} 之間！")]
        public decimal Budget { get; set; }
        [Required]
        public System.DateTime StartDate { get; set; }
    }


    public partial class DepartmentUpdate
    {
        public decimal Budget { get; set; }
    }
}
